
proc format library= work;
	value $site_code	
				"UTI"=	"Urinary Tract Infection"
				"SSI"=	"Surgical Site Infection"
				"PNEU"= "Pneumonia "
				"BSI" =	"Bloodstream Infection"
				"BJ"	=	"Bone and Joint Infection"
				"CNS" =	"Central Nervous System Infection"
				"CVS" =	"Cardiovascular System Infection"
				"EENT"=	"Eye, Ear, Nose, Throat, or Mouth Infection"
				"GI"	=	"Gastrointestinal System Infection"
				"LRI"=	"Lower Respiratory Tract Infection, Other Than Pneumonia"
				"SST"=	"Skin and Soft Tissue Infection"
				;
	value $type_code
				"SUTI"= "Symptomatic urinary tract infection"
				"ASB"=	"Asymptomatic bacteriuria" 
				"OUTI"=	"Other infections of the urinary tract"
				"SKNC"= "Superficial incisional infection at chest incision site, after CBGB"
				"SKNL"= "Superficial incisional infection at vein donor site, after CBGB."
				"ST"= 	"Deep incisional surgical site infection, except after CBGB."
				"STC"=   "After CBGB, report STC for deep incisional surgical site infection at chest incision site."
				"STL"= 	 "After CBGB, report STL for deep incisional surgical site infection at vein donor site."
				"PNU 1"= "PNU1 - Clinically defined pneumonia"
				"PNU 2"= "PNU2 - Pneumonia with specific lab findings"
				"PNU 3"= "PNU3 - Pneumonia in immunocompromised patients"	
				"LCBI"=  "Laboratory-confirmed bloodstream infection"
				"CSEP"=	"Clinical sepsis"
				"BONE"=	"Osteomyelitis"
				"JNT"=	"Joint or bursa"
				"IC"=	"Intracranial infection"
				"MEN"=	"Menitigitis or ventriculitis"
				"SA"=	"Spinal abscess without meningitis"
				"VASC"=	"Arterial or venous infection"
				"ENDO"=	"Endocarditis"
				"CARD"=	"Myocarditis or pericarditis"
				"MED"=	"Mediastinitis"
				"EYE"=	"Eye other than conjunctivitis"
				"ORAL"=	"Oral Cavity (mouth, tongue, or gums)"
				"SINU"=	"Sinusitis"
				"UR"=	"Upper respiratory tract, pharyngitis, laryngitis, epiglottitis"
				"GE"=	"Gastroenteritis"
				"GIT"=	"Gastrointestinal (GI) tract"
				"HEP"=	"Hepatitis"
				"IAB"= 	"Intra-abdominal, not specified elsewhere"
				"BRON"=	"Bronchitis, tracheobronchitis, tracheitis, without evidence of pneumonia"
				"LUNG"=	"Other infections of the lower respiratory tract"
				"ST"=	"Soft tissue"
				"DECU"=	"Decubitus ulcer"
				;

	value cult_org_code
				1 = "Methicillin-susceptible Staphylococcus aureus (MSSA)"
				2 = "Methicillin-resistant Staphylococcus aureus (MRSA)"
				3 = "Coagulase-negative Staphylococcus species" 
				4 = "Vancomycin-susceptible Enterococcus faecalis" 
				5 = "Vancomycin-resistant Enterococcus faecalis" 
				6 = "Vancomycin-susceptible Enterococcus faecium" 
				7 = "Vancomycin-resistant Enterococcus faecium" 
				8 = "Klebsiella pneumoniae" 
				9 = "Other Klebsiella species" 
				10 = "Pseudomonas aeruginosa" 
				11 = "Streptococcus pneumoniae" 
				12 = "Escherichia coli" 
				13 = "Acinetobacter baumannii" 
				14 = "Enterobacter cloace" 
				15 = "Enterobacter aerogenes" 
				16 = "Clostridium difficile" 
				17 = "Candida albicans" 
				18 = "Candida glabrata" 
				19 = "Candida tropicalis" 
				20 = "Other fungal species" 
				21 = "Other"
				;
	
	value cult_site_code
				1 = "Blood" 
				2 = "Urine"
				3 = "Wound" 
				4 = "Sputum / Tracheal Aspirate" 
				5 = "BAL" 
				6 = "CSF"
				7 = "Stool" 
				8 = "Catheter Tip" 
				9 = "Other" 
			;
run;
