data x;
   set glnd.plate1;
   enrolled=1;
   x=put(id,5.);
   if substr(x,2,1)='9' then enrolled=0;
   format enrolled yn.;
   center=substr(x,1,1)+0;
   format center center.;
   grantyr=.;
   if dt_screen<=mdy(8,31,2006) then grantyr=1;
     else if dt_screen<=mdy(8,31,2007) then grantyr=2;
       else if dt_screen<=mdy(8,31,2008) then grantyr=3;
           else if dt_screen<=mdy(8,31,2009) then grantyr=4;
              else if dt_screen<=mdy(8,31,2010) then grantyr=5;
                 else if dt_screen<=mdy(8,31,2011) then grantyr=6;
   keep id x enrolled center grantyr dt_screen;
   if id=39006 then delete;
   proc sort; by grantyr;
   ods pdf file='yearlyscreened.pdf';
   options ls=80 ps=55;
   proc freq;
    tables center*enrolled;
    by grantyr;
    title Enrollment and Screening by Grant Year;
    run;
   ods pdf close;