%inc'patientreportinc.sas';
data pat;
   infile 'patientreport.dat';
    input id;
run;

data single;
   merge all pat(in=a);
    by id;
    if a;
     
file 'patientreport.out';
   put;
   put @5 "ID = " id @20 "MOC Initials = " mocinit;
   put;
   put @5 "Date Enrolled" @20 Enrollmentdate;
   put @5 "Date of Birth" @20 lbwidob;
   put @5 "Time of Birth" @20 lbwitob;
   put @5 "Gender " @20 gender;
   put @5 "Race " @20 race;
   put;
   put @5 "Enrollment Blood and Urine";
   put @5 "--------------------------";
   put @5 "LBWI: Urine Collection Form  " p3;
   if p3=1 then do;
     put @10 "Was Urine Collected  " urinesample;
     if urinesample=1 then put @20 "Date  " urinesampledate;
   end;
   put @5 "MOC Blood Collection Form  " p4;
   if p4=1 then do;
     put @10 "Was Blood Collected for CMV NAT  " natsample;
     if natsample=1 then put @20 "Date  " datenatsample;
     put @10 "Was Blood Collected for CMV Serology  " serologysample;
     if serologysample=1 then put @20 "Date  " dateserologysample;
   end;   
   put;
   put @5 "Enrollment Forms";
   put @5 "------------------------------------------";
   put @10 "LBWI Demographic:" @40 lbwidemo " forms received";
   put @10 "MOC Demographic:" @40 mocdemo " forms received";
  
   put @10 "SNAP" @40 snap " forms received";
   put @10 "LBWI Medical Record Review" @40 p15p16 " forms received";
   put @10 "LBWI Blood Collection" @40 p17 " form received";
   if p17=1 then do;
       put @15 "Was Blood collected form CMV NAT  " natbloodcollect;
       if natbloodcollect=1 then put @40 "Date:  " natblooddate;
   end;
   put @10 "LBWI: CMV NAT Urine Test Result Form  " p200;
   if p200=1 then put @20 "Results:  " urinetestresult;
    put @10 "LBWI: CMV NAT Blood Test Result Form  " p201;
   if p201=1 then put @20 "Results:  " nattestresult;
    put @10 "MOC: CMV NAT Blood Test Result Form  " p203;
   if p203=1 then put @20 "Results:  " nattestresultmoc;
    put @10 "MOC: CMV Serology Test Result Form  " p204;
   if p204=1 then do;
        put @20 " IgG/IgM Results:  " ComboTestResult;
        put @20 " IgM Results:  " igmTestResult;
   end;
   put;
   put @5 "Follow-up Forms";
   put @5 "------------------------------------------";
   if f4>=1 then put @10 'Day 4 ' @30 f4 " forms received";
   if f7>=1 then do;
                   put @10 'Day 7 ' @30 f7 " forms received";
                   put @20 f7optional " optional forms received";
            end;
   if f14>=1 then put @10 'Day 14 ' @30 f14 " forms received";   
   if f21>=1 then do;
                   put @10 'Day 21 ' @30 f21 " forms received";
                   put @20 f21optional " optional forms received";
            end;
   if f25=1 then put @10 "MOC: Placental Infection and Pathology form received";
   if f28>=1 then do;
                   put @10 'Day 28 ' @30 f28 " forms received";
                   put @20 f28optional " optional forms received";
            end;
   if f40>=1 then do;
                   put @10 'Day 40 ' @30 f40 " forms received";
                   put @20 f40optional " optional forms received";
           end;
   if f60>=1 then do;
                   put @10 'Day 60 ' @30 f60 " forms received";
                   put @20 f60optional " optional forms received";
            end;   
    if ivh>=1 then put @10 'IVH' @30 ivh " forms received";
    if bpd>=1 then put @10 'BPD' @30 "form received";
    if rop>=1 then put @10 'ROP' @30 "form received";
    if pda>=1 then put @10 'PDA' @30 "form received";
    if f90>=1 then do;
                   put @10 'End of Study' @30 f90 " form received";
                   put @20 f90optional " optional forms received";
            end;          
 put;                  
 if un>=1 then do; put @10 "Unscheduled NAT forms";
     if ubnat>=1 then put @30 ubnat  " LBWI Blood NAT forms received";
     if uunat>=1 then put @30 uunat  " LBWI Urine NAT  forms received";
     if umnat>=1 then put @30 umnat  " MOC NAT forms received";
 end;
 put;
 if rbc>=1 then put @10 "Red Blood Cell Transfusion " rbc " forms received";
 put;            
 if nvaso>=1 then put @10 "Vasopressor Log forms received";
 if milk>=1 then put @10 "Ever Breast Fed";
 if mvent='Yes' then put @10 "Ever on Ventilator";
 if leftstudy>=1 then put @10 "Left Study on " studyleftdate;
*proc print;
run;
proc contents varnum;
run;
